mysite/dbproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

app_name = 'dbproject'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^impcsv/$', views.impcsv, name='impcsv'),
    url(r'^singlequery/$', views.singlequery, name='singlequery'),
    url(r'^customquery/$', views.customquery, name='customquery'),
    url(r'^prediction/$', views.prediction, name='prediction'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^dbproject/', include('dbproject.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/dbproject/models.py
import datetime

from django.db import models
from django.utils import timezone


class Population(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    age0_5 = models.IntegerField(default=0)
    age6_17 = models.IntegerField(default=0)
    age18_64 = models.IntegerField(default=0)
    age65 = models.IntegerField(default=0)
    agetotal = models.IntegerField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Population._meta.fields]

class StateCode(models.Model):
    state_name = models.CharField(max_length=30)
    alpha_code = models.CharField(max_length=3)
    numeric_code = models.CharField(max_length=3)
    def __str__(self):
        return self.state_name

class Sex(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    male = models.FloatField(default=0)
    female = models.FloatField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Sex._meta.fields]

class Race(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    white = models.IntegerField(default=0)
    black = models.IntegerField(default=0)
    asian = models.IntegerField(default=0)
    native_american = models.IntegerField(default=0)
    other = models.IntegerField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Race._meta.fields]

class Economy(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    gdp = models.IntegerField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Economy._meta.fields]


class Business(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    num_firms = models.IntegerField(default=0)
    num_employees = models.IntegerField(default=0)
    payroll = models.IntegerField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Business._meta.fields]


class Employment(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    unemployment = models.FloatField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Employment._meta.fields]


class HealthInsurance(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    uninsured_rate = models.FloatField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in HealthInsurance._meta.fields]


class Housing(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    homeownership_rate = models.FloatField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Housing._meta.fields]


class Income(models.Model):
    state = models.CharField(max_length=3)
    year = models.IntegerField(default=2010)
    median_hhincome = models.IntegerField(default=0)
    poverty_rate = models.FloatField(default=0)

    def __str__(self):
        return self.state
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Income._meta.fields]

mysite/dbproject/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.db import connection
from collections import namedtuple
from itertools import izip
import csv, sqlite3, os

from .models import Population, StateCode, Sex, Race, Economy, Business, Employment, HealthInsurance, Housing, Income

def index(request):
    states = []
    states = returnstates("test")
    years = range(2010, 2015)
    context = {'states': states, 'years': years}
    return render(request, 'dbproject/index.html', context)


def singlequery(request):
    table_name = request.POST['table']
    state = StateCode.objects.get(state_name=request.POST['state'])
    if table_name == "Population":
        single = Population.objects.get(year=request.POST['year'], state=state.numeric_code)
        context = {'single': single, 'state': request.POST['state']}
    if table_name == "Sex":
        single = Sex.objects.get(year=request.POST['year'], state=state.numeric_code)
        context = {'single': single, 'state': request.POST['state']}
    if table_name == "Race":
        single = Race.objects.get(year=request.POST['year'], state=state.numeric_code)
        context = {'single': single, 'state': request.POST['state']}
    if table_name == "Economy":
        try:
            single = Economy.objects.get(year=request.POST['year'], state=state.numeric_code)
            context = {'single': single, 'state': request.POST['state']}
        except Economy.DoesNotExist:
            error_message = "Sorry, no information for this year."
            context = {'error_message': error_message}
    if table_name == "Business":
        try:
            single = Business.objects.get(year=request.POST['year'], state=state.numeric_code)
            context = {'single': single, 'state': request.POST['state']}
        except Business.DoesNotExist:
            error_message = "Sorry, no information for this year."
            context = {'error_message': error_message}
    if table_name == "Employment":
        single = Employment.objects.get(year=request.POST['year'], state=state.numeric_code)
        context = {'single': single, 'state': request.POST['state']}
    if table_name == "HealthInsurance":
        try:
            single = HealthInsurance.objects.get(year=request.POST['year'], state=state.numeric_code)
            context = {'single': single, 'state': request.POST['state']}
        except HealthInsurance.DoesNotExist:
            error_message = "Sorry, no information for this year."
            context = {'error_message': error_message}
    if table_name == "Housing":
        single = Housing.objects.get(year=request.POST['year'], state=state.numeric_code)
        context = {'single': single, 'state': request.POST['state']}
    if table_name == "Income":
        single = Income.objects.get(year=request.POST['year'], state=state.numeric_code)
        context = {'single': single, 'state': request.POST['state']}
    
    return render(request, 'dbproject/single.html', context)

def customquery(request):
    try:
        query = request.POST['query_sentence']
        cursor = connection.cursor()
        cursor.execute(query)
        results = namedtuplefetchall(cursor)
        p = results[0]
        names = p._fields
        row = 0
        col = 0
        values = [[0 for x in range(len(names))] for x in range(len(results))] 
        for p in results:
            for name in p._fields:
                if name == "state":
                    state = StateCode.objects.get(numeric_code=getattr(p, name))
                    values[row][col] = state.state_name
                    col += 1
                else:
                    values[row][col] = getattr(p, name)
                    col += 1
            row += 1
            col = 0
        print(values[0])
        context = {'names': names, 'values': values}
        return render(request, 'dbproject/customquery.html', context)
    except :
        context = {'error_message': "There may be some error in the query sentence."}
        return render(request, 'dbproject/customquery.html', context)

def prediction(request):
    try:
        pGDP = float(request.POST['gdp'])
        mHIncome = pGDP * 0.88818
        context = {'mHIncome': mHIncome, 'pGDP': pGDP}
        return render(request, 'dbproject/prediction.html', context)
    except :
        context = {'error_message': "Please type in valid float number."}
        return render(request, 'dbproject/prediction.html', context)
    
def returnstates(params):
    states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
    "Connecticut", "Delaware", "District Of Columbia", "Florida", "Georgia", "Hawaii", 
    "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", 
    "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", 
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", 
    "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", 
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
    "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", 
    "Wyoming"]
    return states

def impcsv(request):
    states=[]
    states = returnstates("test")
    years = range(2010, 2015)
    context = {'states': states, 'years': years, 'imported': "imported"}

    StateCode.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'StateCode.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            StateCode.objects.create(
                state_name=row[0],
                alpha_code=row[1],
                numeric_code=row[2]
                )

    Population.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Population.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Population.objects.create(
                state=row[0],
                year=row[1],
                age0_5=row[2],
                age6_17=row[3],
                age18_64=row[4],
                age65=row[5],
                agetotal=row[6],
                )

    Sex.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Sex.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Sex.objects.create(
                state=row[0],
                year=row[1],
                male=row[2],
                female=row[3]
                )

    Race.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Race.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Race.objects.create(
                state=row[0],
                year=row[1],
                white=row[2],
                black=row[3],
                asian=row[4],
                native_american=row[5],
                other=row[6]
                )

    Economy.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Economy.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Economy.objects.create(
                state=row[0],
                year=row[1],
                gdp=row[2]
                )

    Business.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Business.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Business.objects.create(
                state=row[0],
                year=row[1],
                num_firms=row[2],
                num_employees=row[3],
                payroll=row[4],
                )

    Employment.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Employment.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Employment.objects.create(
                state=row[0],
                year=row[1],
                unemployment=row[2],
                )

    HealthInsurance.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'HealthInsurance.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            HealthInsurance.objects.create(
                state=row[0],
                year=row[1],
                uninsured_rate=row[2],
                )

    Housing.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Housing.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Housing.objects.create(
                state=row[0],
                year=row[1],
                homeownership_rate=row[2],
                )

    Income.objects.all().delete()
    file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'Income.csv'))
    with open(file_path) as f:
        reader = csv.reader(f, delimiter=",")
        for row in reader:
            Income.objects.create(
                state=row[0],
                year=row[1],
                median_hhincome=row[2],
                poverty_rate=row[3],
                )
    return render(request, 'dbproject/index.html', context)

def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    print(nt_result)
    return [nt_result(*row) for row in cursor.fetchall()]

mysite/dbproject/templates/dbproject/customquery.html
<html>
	<!-- Head of the index page. -->
	<head>
		<title>US Census Data.</title>
		<style>
			.div-inline{ display:inline} 

			.table-caption{ font-size: 13px; letter-spacing: 0.5px; text-transform: uppercase; padding: 8px; font-weight: 400; text-align: left; background: #79aec8; color: #fff; }

			.table-whole{ border-color: #CCC; border-collapse: collapse; border-collapse: separate; border-spacing: 2px; width: 100%; }

			.td-type{font-size: 13px; line-height: 16px; border-bottom: 1px solid #eee;vertical-align: top; padding: 8px; font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;}

			.selection{color: #447e9b; display:-moz-inline-box; display:inline-block; width: 200px; text-align: center}

			table{ margin: auto;}
		</style>
	</head>
	<!-- End of the head. -->
	<body>
		<div style="position: relative; width: 100%; min-width: 980px; padding: 0">
			<!-- Headbar of the index page. -->
			<div style="width: auto; height: 40px; padding: 10px 40px; background: #417690; line-height: 40px; color: #ffc; overflow: hidden;">
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 200; font-size: 24px; color: #f5dd5d;">
					Database Project
				</div>
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 50; font-size: 15px; color: #f5dd5d;">
					Made by Bowen Li and Dongrui Zhong.
				</div>
			</div>
			<!-- End of the headbar. -->

			<div style="padding: 20px 40px">
				<h1 style="margin: 0 0 20px; font-weight: 50; font-size: 20px; color: #666;">
					Show Result
				</h1>
				<div style="margin-bottom: 30px;">
					<table class="table-whole">
						<caption class="table-caption">
							CUSTOM QUERY
						</caption>
					</table>
					<div style="vertical-align: inherit; border-color: inherit; padding: 30 0 0 5px; text-size: 20px; min-height: 100px ">
						
						<table border="1" cellpadding="10" style="align: center">
							{% if error_message %}
								{{ error_message }}
								<br><br>
								<div style="text-size: 13px">
									P.S. Please select specific column that you want, as duplicate column names may raise problems.
								</div>
							{% else %}
							    <tbody>
							    	<tr>
								    	{% for name in names %}
								    		
										    <th>{{ name }}</th> 
										{% endfor %}	
									</tr>
									{% for row in values %}
										<tr>
											{% for value in row %}
										        <th>{{ value }}</th> 
										    {% endfor %}
										</tr>
									{% endfor %}
								</tbody>
							{% endif %}
						</table>

					</div>
				</div>
				<!-- End of Simple Queries. -->
			</div>
			<div style="padding: 20px 40px">
				<form action="{% url 'dbproject:index' %}" style="margin-bottom: 0">
					<input type="submit" value="Back" style="font-size: 15px;">
				</form>
			</div>
		</div>
	</body>
</html>

mysite/dbproject/templates/dbproject/index.html
<html>
	<!-- Head of the index page. -->
	<head>
		<title>US Census Data.</title>
		<style>
			.div-inline{ display:inline} 

			.table-caption{ font-size: 13px; letter-spacing: 0.5px; text-transform: uppercase; padding: 8px; font-weight: 400; text-align: left; background: #79aec8; color: #fff; }

			.table-whole{ border-color: #CCC; border-collapse: collapse; border-collapse: separate; border-spacing: 2px; width: 100%; }

			.td-type{font-size: 13px; line-height: 16px; border-bottom: 1px solid #eee;vertical-align: top; padding: 8px; font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;}

			.selection{color: #447e9b; display:-moz-inline-box; display:inline-block; width: 200px; text-align: center}
		</style>
	</head>
	<!-- End of the head. -->
	<body>
		<div style="position: relative; width: 100%; min-width: 980px; padding: 0";>
			<!-- Headbar of the index page. -->
			<div style="width: auto; height: 40px; padding: 10px 40px; background: #417690; line-height: 40px; color: #ffc; overflow: hidden;">
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 200; font-size: 24px; color: #f5dd5d;">
					Database Project
				</div>
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 50; font-size: 15px; color: #f5dd5d;">
					Made by Bowen Li and Dongrui Zhong.
				</div>
			</div>
			<!-- End of the headbar. -->

			<!-- Import button of csv. -->
			<div style="padding: 20 40 0 40px; ">
				{% if imported %}
					<p>
						<strong>
							CSV has been imported.
						</strong>
					</p>
				{% else %}
					<form action="{% url 'dbproject:impcsv' %}" style="margin-bottom: 0">
						<input type="submit" value="Import CSV" style="font-size: 15px;">
					</form>
				{% endif %}
				
			</div>
			<!-- End of importing CSV. -->

			<!-- Start three boxes of querying. -->
			<div style="padding: 20px 40px">
				<h1 style="margin: 0 0 20px; font-weight: 50; font-size: 20px; color: #666;">
					Begin operation
				</h1>
				<div style="margin-bottom: 30px;">
					<table class="table-whole">
						<caption class="table-caption">
							QUERY FROM DATABASE
						</caption>
					</table>
					<div style="vertical-align: inherit; border-color: inherit;">
						<form action="{% url 'dbproject:singlequery' %}" method="post" style="padding: 10 0 0 5px;">
							{% csrf_token %}
							<span class="selection">
								<div>From which table:</div>
								<br>
								<select name="table">
									<option value="Population">Population</option>
									<option value="Sex">Sex</option>
									<option value="Race">Race</option>
									<option value="Economy">Economy</option>
									<option value="Business">Business</option>
									<option value="Employment">Employment</option>
									<option value="HealthInsurance">HealthInsurance</option>
									<option value="Housing">Housing</option>
									<option value="Income">Income</option>
								</select>
							</span>
							<span class="selection">
								<div>Select a year:</div>
								<br>
								<select name="year">
									{% for year in years %}
								        <option value={{ year }}>
								        	{{ year }}
								        </option>
								    {% endfor %}
								</select>
							</span>
							<span class="selection" style="margin-right: 100px">
								<div>Select a state:</div>
								<br>
								<select name="state">
									{% for state in states %}
								        <option value="{{ state }}">
								        	{{ state }}
								        </option>
								    {% endfor %}
								</select>
							</span>
							<input type="submit" value="Submit" style="text-align:center"/>
						</form>
					</div>
				</div>
				<!-- End of Simple Queries. -->

				<!-- Start Prediction part. -->
				<div style="margin-bottom: 30px;">
					<table class="table-whole">
						<caption class="table-caption">
							PREDICTION AND CLASSIFICATION 
						</caption>
					</table>
					<div style="vertical-align: inherit; border-color: inherit;">
						<form action="{% url 'dbproject:prediction' %}" method="post" style="padding: 10 0 0 5px; ">
							{% csrf_token %}
							<div style="margin-bottom: 10px; color: #447e9b">
								Type the Percapita GDP, then we will predict the median household income using regression model:
							</div>
							<input type="text" name="gdp" style="min-width: 200px">
							<input type="submit" value="Submit" style="text-align:center"/>
						</form>
					</div>
				</div>
				<!-- End of Prediction. -->

				<!-- Start of custom queries. -->
				<div style="margin-bottom: 30px;">
					<table class="table-whole">
						<caption class="table-caption">
							CUSTOM QUERY
						</caption>
					</table>
					<div style="vertical-align: inherit; border-color: inherit;">
						<form action="{% url 'dbproject:customquery' %}" method="post" style="padding: 10 0 0 5px; ">
							{% csrf_token %}
							<div style="margin-bottom: 10px; color: #447e9b">
								Type a SQLite query here:
							</div>
							<div style="margin-bottom: 10px; color: #447e9b; font-size: 15px">
								Note when querying, use "dbproject_" as the prefix of all tables following with all small cases table names. e.g. "SELECT * FROM dbproject_housing".
							</div>
							<input type="text" name="query_sentence" style="min-width: 500px">
							<input type="submit" value="Submit" style="text-align:center"/>
						</form>
					</div>
				</div>
				<!-- End of Custom query. -->
			</div>
		</div>
	</body>
</html>

mysite/dbproject/templates/dbproject/prediction.html
<html>
	<!-- Head of the index page. -->
	<head>
		<title>US Census Data.</title>
		<style>
			.div-inline{ display:inline} 

			.table-caption{ font-size: 13px; letter-spacing: 0.5px; text-transform: uppercase; padding: 8px; font-weight: 400; text-align: left; background: #79aec8; color: #fff; }

			.table-whole{ border-color: #CCC; border-collapse: collapse; border-collapse: separate; border-spacing: 2px; width: 100%; }

			.td-type{font-size: 13px; line-height: 16px; border-bottom: 1px solid #eee;vertical-align: top; padding: 8px; font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;}

			.selection{color: #447e9b; display:-moz-inline-box; display:inline-block; width: 200px; text-align: center}

			table{ margin: auto;}
		</style>
	</head>
	<!-- End of the head. -->
	<body>
		<div style="position: relative; width: 100%; min-width: 980px; padding: 0">
			<!-- Headbar of the index page. -->
			<div style="width: auto; height: 40px; padding: 10px 40px; background: #417690; line-height: 40px; color: #ffc; overflow: hidden;">
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 200; font-size: 24px; color: #f5dd5d;">
					Database Project
				</div>
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 50; font-size: 15px; color: #f5dd5d;">
					Made by Bowen Li and Dongrui Zhong.
				</div>
			</div>
			<!-- End of the headbar. -->

			<div style="padding: 20px 40px">
				<h1 style="margin: 0 0 20px; font-weight: 50; font-size: 20px; color: #666;">
					Show Result
				</h1>
				<div style="margin-bottom: 30px;">
					<table class="table-whole">
						<caption class="table-caption">
							PREDICTION
						</caption>
					</table>
					<div style="vertical-align: inherit; border-color: inherit; padding: 30 0 0 5px; text-size: 20px; min-height: 100px ">
						
						{% if error_message %}
							{{ error_message }}
						{% else %}
							The predicted result median household income is {{ mHIncome }} for per capita GDP: {{ pGDP }}
						{% endif %}

					</div>
				</div>
				<!-- End of Simple Queries. -->
			</div>
			<div style="padding: 20px 40px">
				<form action="{% url 'dbproject:index' %}" style="margin-bottom: 0">
					<input type="submit" value="Back" style="font-size: 15px;">
				</form>
			</div>
		</div>
	</body>
</html>

mysite/dbproject/templates/dbproject/single.html
<html>
	<!-- Head of the index page. -->
	<head>
		<title>US Census Data.</title>
		<style>
			.div-inline{ display:inline} 

			.table-caption{ font-size: 13px; letter-spacing: 0.5px; text-transform: uppercase; padding: 8px; font-weight: 400; text-align: left; background: #79aec8; color: #fff; }

			.table-whole{ border-color: #CCC; border-collapse: collapse; border-collapse: separate; border-spacing: 2px; width: 100%; }

			.td-type{font-size: 13px; line-height: 16px; border-bottom: 1px solid #eee;vertical-align: top; padding: 8px; font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;}

			.selection{color: #447e9b; display:-moz-inline-box; display:inline-block; width: 200px; text-align: center}

			table{ margin: auto;}
		</style>
	</head>
	<!-- End of the head. -->
	<body>
		<div style="position: relative; width: 100%; min-width: 980px; padding: 0">
			<!-- Headbar of the index page. -->
			<div style="width: auto; height: 40px; padding: 10px 40px; background: #417690; line-height: 40px; color: #ffc; overflow: hidden;">
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 200; font-size: 24px; color: #f5dd5d;">
					Database Project
				</div>
				<div class="div-inline" style="padding: 0; margin: 0 20px 0 0; font-weight: 50; font-size: 15px; color: #f5dd5d;">
					Made by Bowen Li and Dongrui Zhong.
				</div>
			</div>
			<!-- End of the headbar. -->

			<div style="padding: 20px 40px">
				<h1 style="margin: 0 0 20px; font-weight: 50; font-size: 20px; color: #666;">
					Show Result
				</h1>
				<div style="margin-bottom: 30px;">
					<table class="table-whole">
						<caption class="table-caption">
							QUERY FROM DATABASE
						</caption>
					</table>
					<div style="vertical-align: inherit; border-color: inherit; padding: 30 0 0 5px; text-size: 20px; min-height: 100px ">
						{% if error_message %}
							{{ error_message }}
						{% else %}
							<table border="1" cellpadding="10" style="align: center">
							    <tbody>
							    	<tr>
							    		<th>state</th>
								    	{% for name, value in single.get_fields %}
											{% if name != "id" and name != "state" %}
										        <th>{{ name }}</th> 
											{% endif %}
										{% endfor %}
									</tr>
									<tr>
							    		<th>{{ state }}</th>
								    	{% for name, value in single.get_fields %}
											{% if name != "id" and name != "state" %}
										        <th>{{ value }}</th> 
											{% endif %}
										{% endfor %}
									</tr>
								</tbody>
							</table>
						{% endif %}
					</div>
				</div>
				<!-- End of Simple Queries. -->
			</div>
			<div style="padding: 20px 40px">
				<form action="{% url 'dbproject:index' %}" style="margin-bottom: 0">
					<input type="submit" value="Back" style="font-size: 15px;">
				</form>
			</div>
		</div>
	</body>
</html>